services: mongodb
language: node_js
node_js:
  - lts/*
install:
  - npm install --no-save booljs @booljs/express @booljs/passport \
      passport passport-http passport-http-bearer \
      oauth2orize passport-oauth2-client-password
  - npm install

deploy:
  provider: npm
  email: hola@pablodorado.com
  api_key: $NPM_API_KEY
  on:
    branch: master
    tags: true
