services: mongodb
language: node_js
node_js:
  - lts/*
install:
  - npm install --no-save booljs @booljs/express @booljs/passport \
      passport passport-http passport-http-bearer \
      oauth2orize passport-oauth2-client-password
  - npm install
